#!/usr/bin/env python3
"""Generate the config key tables of docs/reference.md from scripts/pipeline-defaults.sh.

  python3 tests/gen-config-table.py                 print the tables
  python3 tests/gen-config-table.py --write FILE    rewrite the block in FILE between
                                                    the START and END markers
  python3 tests/gen-config-table.py --check FILE    exit 1 when that block differs

The defaults table (one TSV row per key: key, type, default, derived, env override,
scope) is the single source of truth; the docs never carry a second copy.
tests/test-docs-config-table.sh runs --check, so a change to the table fails the
suite until the docs are regenerated with --write.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULTS = os.path.join(ROOT, "scripts", "pipeline-defaults.sh")
START = "<!-- config-table:start (generated by tests/gen-config-table.py; do not edit) -->"
END = "<!-- config-table:end -->"


def rows():
    src = open(DEFAULTS).read()
    m = re.search(r"<<'(TALOS_\w+)' \|\| true\n(.*?)\n\1\n", src, re.S)
    if not m:
        sys.exit("gen-config-table: no defaults table in %s" % DEFAULTS)
    out = []
    for line in m.group(2).split("\n"):
        f = line.split("\t")
        if len(f) != 6:
            sys.exit("gen-config-table: malformed row %r" % line)
        out.append(f)
    return out


def cell(text):
    return "`%s`" % text.replace("|", "\\|") if text else "-"


def render():
    groups = []
    by = {}
    for key, typ, default, derived, env, scope in rows():
        g = key.split(".")[0] if "." in key else "(top level)"
        if g not in by:
            by[g] = []
            groups.append(g)
        d = "derived" if derived == "derived" else default.replace("\\n", ", ")
        by[g].append((key, typ, d, env, scope))
    out = []
    for g in groups:
        out.append("#### %s\n" % (g if g.startswith("(") else g + ".*"))
        out.append("| Key | Type | Default | Env override | Scope |")
        out.append("|---|---|---|---|---|")
        for key, typ, d, env, scope in by[g]:
            dcol = "derived" if d == "derived" else cell(d)
            out.append("| `%s` | %s | %s | %s | %s |" % (
                key, typ, dcol, "-" if env == "-" else "`%s`" % env, scope))
        out.append("")
    return "\n".join(out).rstrip("\n")


def block():
    return "%s\n\n%s\n\n%s" % (START, render(), END)


def current(text):
    i, j = text.find(START), text.find(END)
    if i < 0 or j < 0 or j < i:
        sys.exit("gen-config-table: markers not found")
    return text[i:j + len(END)]


def main(argv):
    if len(argv) == 1:
        print(render())
        return 0
    if len(argv) == 3 and argv[1] in ("--write", "--check"):
        text = open(argv[2]).read()
        old = current(text)
        new = block()
        if argv[1] == "--check":
            return 0 if old == new else 1
        open(argv[2], "w").write(text.replace(old, new))
        return 0
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
